### ISSUE TITLE
recommend my blog on Apple TV development http://pragma.tv

### ISSUE THREAD

**Issue by NilStack** [sanketfirodiya/tvOS#1]
Hi, Sanket:
I recommend my own blog on Apple TV development http://pragma.tv . If you think it's helpful, please add to your list.

I don't know if an issue is proper to recommend a link, or you prefer a pull request?

Thanks for creating this list.

Peng

**Comment by sanketfirodiya** [comment]
Thanks for the link, added!

**Comment by NilStack** [comment]
Thanks, Sanket.
